# Generated by Django 5.2 on 2025-04-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_portfolio_image_alter_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
