# Generated by Django 5.2 on 2025-04-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_portfolio_image_remove_service_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
